### ISSUE TITLE
Consider Separation between UI and Services

### ISSUE THREAD

**Issue by aaime** [geoserver/geofence#1]
<a href="https://github.com/simboss"><img src="https://avatars.githubusercontent.com/u/693880?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [simboss](https://github.com/simboss)**
_Tuesday May 15, 2012 at 10:05 GMT_
_Originally opened as https://github.com/geosolutions-it/geofence/issues/8_

---

We might want to be able to separate the deploy of the UI and the Back-End of GeoFence using Spring Remoting or REST as a connection mechanism.

**Comment by etj** [comment]
Since the integration of GeoFence into GeoServer, this issue may not be relevant anymore.
