### ISSUE TITLE
[Geofence GS plugin] webapp entrypoint set to GWC instead of the regular GS UI

### ISSUE THREAD

**Issue by pmauduit** [geoserver/geofence#102]
When Geofence is integrated to GeoServer, instead of being redirected from `/geoserver` to `/geoserver/web` as expected on a regular (i.e. no geofence) setup, the main page of GeoWebCache is displayed instead.

Steps to reproduce:

1. Download the latest version of GeoServer WAR
2. Download the latest Geofence GS module
3. Unzip the WAR into its own directory, copy the GF jar files into `WEB-INF/lib`
3. using docker:

```
% docker run -it --rm -v `pwd`/geoserver:/var/lib/jetty/webapps/geoserver -p8080:8080 -u0 jetty 
```   
4. Load http://localhost:8080/geoserver/ : a basic auth is popped and discarding it gives the GeoWebCache UI. Note: navigating to http://localhost:8080/geoserver/web/ gives the expected geoserver UI, but it seems to break the REST interface.

**Comment by nmco** [comment]
I gave it a quick try and I confirm this is happening with the geonfence extension, is worth notice that this doesn't
happen with the integrated geofence version, i.e. geofence-server community module.

The same issue was reported and fixed for the geofence-server community module:

  * https://osgeo-org.atlassian.net/browse/GEOS-8331

  * https://github.com/geoserver/geoserver/pull/2591

Can you open a GeoServer JIRA issue for this ?

**Comment by afabiani** [comment]
This has been already solved, you need to add the following property

gwc.context.suffix=gwc

into the "geofence-server.properties" file

**Comment by pmauduit** [comment]
Ok thanks, and sorry for having missed the ticket on JIRA

**Comment by jeanmi151** [comment]
I had the very same issue with last version of geoserver-geofence (2.22.2)
Found here the solution : https://gis.stackexchange.com/questions/408565/geoserver-homepage-is-showing-geowebcache-homepage 
by adding to the var  JAVA_OPTS (option added for run) this : `-Dgwc.context.suffix=gwc`
It fix the issue
