### ISSUE TITLE
Why is there a backdoor here ?

### ISSUE THREAD

**Issue by jusabatier** [geoserver/geofence#105]
https://github.com/geoserver/geofence/blob/f74fd0e0dae19294df220d5ccf6c9aacd9ad7264/src/gui/core/plugin/userui/src/main/java/org/geoserver/geofence/gui/server/service/impl/LoginService.java#L79

**Comment by bradh** [comment]
Looks like its from the initial commit: https://github.com/geoserver/geofence/commit/bcf49d3e4bc1d886559165e7c72628dc4cb10f77

@aaime any insight?

**Comment by aaime** [comment]
It was already there, from the old repos. We are looking into it.

**Comment by nmco** [comment]
The old repositories which are not used anymore have been removed. Regarding GeoFence repository, this one, two things should be done:

1. Remove the related code, i.e. the backdoor.
2. Clean the repository history that has any reference to this portion of code.

The second step means that any checkout, pending pull requests (currently four) will have to resync, this will require a bit of work, something like:

1. Create a new branch
2. Cherry-pick the necessary commits from the old branch

Thoughts on this ?

**Comment by nmco** [comment]
I'm proceeding with the plan above.
