### ISSUE TITLE
Update docs for 2.14 

### ISSUE THREAD

**Issue by mikefedak** [geoserver/geofence#116]
Hello, 

I notice that the last build available here: http://ares.opengeo.org/geoserver/master/community-latest/ is for geoserver 2.13. I also notice that the github as well as boundless (https://repo.boundlessgeo.com/release/org/geoserver/community/gs-geofence-server/2.14.0/) have put up newly updated versions. Is there a plan to release a nicely packaged archive for geofence for 2.14?

**Comment by afabiani** [comment]
2.15 -> https://build.geoserver.org/geoserver/master/ext-latest/

2.14 -> https://build.geoserver.org/geoserver/2.14.x/community-latest/
