### ISSUE TITLE
Geofence war links are not working.

### ISSUE THREAD

**Issue by majkshkurti** [geoserver/geofence#126]

**Comment by etj** [comment]
Current links are like this:
http://build.geoserver.org/geofence/3.4.x/release-v3.4.1-geofence-war.zip

- The server now supports https only.
- GeoFence artifacts seem to be swept away (check into https://build.geoserver.org/geofence/ subdirs)

**Comment by etj** [comment]
See #129

**Comment by etj** [comment]
`war` files are now deployed in github releases: https://github.com/geoserver/geofence/releases
