### ISSUE TITLE
Permissions for adding a store

### ISSUE THREAD

**Issue by richardtc** [geoserver/geofence#136]
I'm using GeoServer 2.16.0 and would like to set permissions where a user can only access a specific directory on the server to select a file for creating a store. I have a GeoServer with multiple users and would like each user to have access to a specific directory. Does Geofence provide such functionality?

**Comment by nmco** [comment]
I don't think this is currently supported, and not sure there is something in GeoServer ecosystem that will allow you to do this, you may want to send a mail to GeoServer users list.

**Comment by etj** [comment]
GeoFence only manages permissions for layers, workspace, services, that is for GeoServer logical objects, and not for physical storage areas (filesystem, db, ...).
