### ISSUE TITLE
"Admin rules" grants "ADMIN" access to unauthorized user

### ISSUE THREAD

**Issue by petermozolik** [geoserver/geofence#140]
Hi,

According to my understanding of how "Admin rules" work (trial and error method used, as I was not able to find usefull docs on "Admin rules"), Geofence Internal Server extension "Admin rules" **allows unathorized access to workspace** which is serious problem for me and in fact usage blocker.

I tried to discuss this issue before bringing it here on Geoserver User-list with no success.
[http://osgeo-org.1560.x6.nabble.com/Goeofence-admin-rules-issues-td5440722.html]

Environment: 
OS: Ubuntu 20.04
JVM: Private Build: 1.8.0_252 (OpenJDK 64-Bit Server VM) 
GeoServer instance is running version 2.17.1.
Geofence Internal Server extension for Geoserver 2.17.1

1) Two users in "default" User Group service 

- sf_admin
- topp_admin

2) Two roles in "default" Role service
- ROLE_SF_ADMIN
- ROLE_TOPP_ADMIN

3) Users have directly assigned respective roles (no user Groups are used)
- sf_admin -> ROLE_SF_ADMIN
- topp_admin -> ROLE_TOPP_ADMIN

4) Two worskpaces with some layers (from default Geoserver installation)
- sf
- topp

5) GeoFence Admin Rules
P Role             User Workspace  Access
1 ROLE_TOPP_ADMIN  *    topp       ADMIN
2 ROLE_SF_ADMIN    *    sf         ADMIN
This setup leads me to expectations that users are able to edit respective workspace configuration.

**Problem:**
User "sf_admin" (when logged) is able to edit both workspaces configuration ie. "sf" and "topp"
User "sf_topp" (when logged) is able to edit both workspaces configuration ie. "sf" and "topp"

So both users can access configuration of both worksapaces, despite the fact that Geofence Admin rules selectively grants (based on ROLE) admin access for users to respective workspace!!!

Thank you

**Comment by groldan** [comment]
Hi, run into this issue after being assigned to look into this same problem found at work.
So far my understanding is GeoFence itself does not/cannot enforce the rules. Instead, it works mostly as a plain CRUD repository service. Hence, as long as the rules are saved correctly, the issue shall be tackled at geoserver's side where the rules ought to be enforced.

Keep you posted on my findings, let's hope I can fix it.

**Comment by groldan** [comment]
Closing as fixed by #5109 back in April 2022
