### ISSUE TITLE
Can't access the rest api when using geoserver integrated geofence

### ISSUE THREAD

**Issue by zoran995** [geoserver/geofence#157]
When using a GeoFence integrated into Geoserver the rest API throws an error `java.lang.NoClassDefFoundError: org/codehaus/stax2/ri/Stax2WriterAdapter`. 
The error seems to be coming from the missing `stax2-api` dependency, adding of the https://mvnrepository.com/artifact/org.codehaus.woodstox/stax2-api/4.2.1 to Geoserver lib solved the issue.

**Comment by etj** [comment]
- [ ] check and add the missing lib
- [ ] perform client tests against geoserver
- [ ] add some doc for the various integration test 
  - testing REST calls with geofence standalone
  - testing auth calls from geoserver (`geofence` plugin) toward geofence standalone
  - test REST calls toward geoserver (`geofence-server` plugin)
