### ISSUE TITLE
Geoserver - layer attribute limit and order of attributes in GetFeatureInfo requests

### ISSUE THREAD

**Issue by dracic** [geoserver/geofence#158]
When we use layer attribute limit, geofence inserts layer and attribute names and limit rules to gf_layer_attributes table but with no particular order. First time you access geoserver rule, attributes are displayed in order they are displayed in 
Feature Type Details of layer properties. Next time you access the GUI attributes are displayed completely different. I think it is important to keep that attribute order because when you apply the rule attribute order gets messed up when using GetfeatureInfo request and also when we want to edit the rule. We all have some logic in the way attributes are ordered in our tables. Perhaps it's not due to the order of attributes in gf_layer_attributes, maybe it has to be with how this rules are applied and responses served back to users? However they should be ordered properly in gf_layer_attributes because of Geofence GUI.

**Comment by dracic** [comment]
Just to add one thing. This happens when using PostGIS backend. I haven't tested this on H2 dB.

**Comment by dracic** [comment]
I also can see that when attribute limit is applied on a layer, GetFeatureInfo response from Geoserver sorts attributes randomly so on every request i get different result.

**Comment by dracic** [comment]
Creating the rule:
![geofence1](https://user-images.githubusercontent.com/4533263/97991192-5ffa0500-1de1-11eb-884e-4c99ae6b96c6.jpg)

Editing the rule:
![geofence2](https://user-images.githubusercontent.com/4533263/97991199-62f4f580-1de1-11eb-8a9e-82567775be6e.jpg)

**Comment by dracic** [comment]
I had a discussion with Ian on mailing list:

[http://osgeo-org.1560.x6.nabble.com/Geoserver-2-10-amp-external-Geofence-3-2-GetFeatureInfo-problem-td5329591.html#a5330161](url)

I am aware that GeoServer and the WMS specification make no promises as to the attribute order in a GetFeatureInfo request. But if unrestricted GetfeatureInfo always lists attributes in order they are listed in Feature Type Details of layer properties, then the behavior od restricted layer should be the same. 

I'm not familiar with java but I suppose that attributes are collected to some kind of unordered hashtable object and that way we loose attribute order when inserting into  gf_layer_attributes table.

**Comment by etj** [comment]
This is a geoserver related issue, not geofence. Closing.
