### ISSUE TITLE
Preserve the SRID of allowed area when retrieving it through AccessInfo

### ISSUE THREAD

**Issue by taba90** [geoserver/geofence#161]
When the AccessInfo object is built from a Rule, the SRID of the Geometry is not included in the WKT representation of allowedArea.

**Comment by etj** [comment]
Merged in 3.4.x: https://github.com/geoserver/geofence/pull/162

**Comment by etj** [comment]
Adding a note that has been discussed by voice: simply storing the SRID in the geometries in not enough: GeoFence performs some operations (union, intersect) with the internal geometries, so, if geometries have different SR, they need to be reprojected.
