### ISSUE TITLE
Update compatibility matrix in the wiki

### ISSUE THREAD

**Issue by randomorder** [geoserver/geofence#177]
The [Getting GeoFence](https://github.com/geoserver/geofence/wiki#getting-geofence) section at the root of the wiki is not aligned with the [compat matrix](https://github.com/geoserver/geofence/wiki/Compatibility-matrix-(GS-2.17-2.19,-GF-3.4.x-3.5.x))

**Comment by etj** [comment]
Removed resource links in the wiki page, current links are in the root [README](https://github.com/geoserver/geofence/blob/master/README.markdown) file.

**Comment by randomorder** [comment]
cool, thank you!

**Comment by etj** [comment]
Also, there should be some issues in the artifacts deployment, see #179
