### ISSUE TITLE
Fix build server config

### ISSUE THREAD

**Issue by etj** [geoserver/geofence#179]
The artifact seems not to be placed in the right location, since https://build.geoserver.org/geofence/ is empty.

Pls check configuration from geoserver builds, since artifacts are properly deployed there: https://build.geoserver.org/geoserver/

Also, fix links in the README file accordingly once artifact deployment is working.

**Comment by randomorder** [comment]
looks good now, thanks @etj 
https://build.geoserver.org/geofence/
