### ISSUE TITLE
How to download a pdf layer via rest API

### ISSUE THREAD

**Issue by djuwa4** [geoserver/geofence#181]
Good day! Tell me please: how to download a pdf layer via rest API.
To concretize, I just need to download in PDF or JPG for example a layer with the name: topp: states
I know how to look at the list of layers:
curl -u test: test -XGET http://10.10.1.144:8080/geoserver/rest/layers
But how to download a specific layer to the local computer, I can't find any information.

**Comment by simboss** [comment]
Please, use the GeoServer mailing.
This is not material for an issue, especially on GeoFence.

**Comment by djuwa4** [comment]
I do not quite understand what kind of mailing, can you tell us more about it? Thank you in advance!

**Comment by djuwa4** [comment]
> Пожалуйста, воспользуйтесь рассылкой GeoServer.
> Это не имеет значения для выпуска, особенно для GeoFence.

Я не совсем понимаю, что это за рассылка, расскажите о ней поподробнее? Заранее спасибо!

**Comment by djuwa4** [comment]
> Please, use the GeoServer mailing.
> This is not material for an issue, especially on GeoFence.

I do not quite understand what kind of mailing. Please tell me more about this. Thank you in advance!
