### ISSUE TITLE
Geoserver WFS problem

### ISSUE THREAD

**Issue by satrock1** [geoserver/geofence#213]
I have more than 400 users, each has its own layer view area on the map, I was able to implement this using Geofence, I added layers to the layer group in GeoServer, and configured roles in Geofence for users. In GeoServer in the "View layers" everything works well and all layers are displayed correctly in their territories.

But when I open my site with a map built on the Leaflet plugin, the WMS layers are displayed correctly, and the WFS layers are not displayed as expected, they are displayed on the entire map. For WFS layers I use the Leaflet-WFST plugin. How can I make WFS layers display correctly with a territory limit how it works with WMS layers?

I think the problem is not in my code, because if the WFS layer is made separately from the layer group and set to WKT, then the territory restrictions will work on the web page. But this option is not suitable, since I will need to duplicate this stand so many times with other WKTs, and I also have a lot of vector layers and they will also have to be duplicated, which is why I made a group of layers. So that you can implement this on your own, just add layers to Geoserver, then to a layer group and try to display it on a WEB map (not in Geoserver), and you can take the base code from the Leaflet-WFST plugin. Geoserver 2.20.4

**Comment by etj** [comment]
@satrock1 Please include some sample rules you created.

**Comment by etj** [comment]
Missing info, won't investigate.
