### ISSUE TITLE
geofence server embedded 2.21.2 breaks the geoserver/gwc access

### ISSUE THREAD

**Issue by gregvds** [geoserver/geofence#235]
deploying the geofence server plugin 2.21.2 embedded into a geoserver 2.21.2 vanilla seems to break the access to localhost:8080/geoserver/gwc/home. This page is still accessible, but under localhost:8080/geoserver. Usually, this redirects to geoserver/web/.

This happens with or without other plugins installed.

adding gwc.context.suffix=gwc in geofence-server.properties does not fix this

**Comment by etj** [comment]
It seems that since 2.20.6 the properties are handled in a different way.

**Comment by etj** [comment]
@gregvds can you pls try adding `-Dgwc.context.suffix=gwc` to the GeoServer JAVA_OPTS?
