### ISSUE TITLE
Create a GS extension for GeoFence probe

### ISSUE THREAD

**Issue by aaime** [geoserver/geofence#25]
<a href="https://github.com/etj"><img src="https://avatars.githubusercontent.com/u/717359?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [etj](https://github.com/etj)**
_Tuesday Jun 24, 2014 at 17:00 GMT_
_Originally opened as https://github.com/geosolutions-it/geofence/issues/100_

---

Create GS community module for versions 2.2, 2.4, 2.5.

Build GeoServer with profile `-Pgeofence` to include it.

**Comment by etj** [comment]
Done long long long time ago
