### ISSUE TITLE
Review GeoFence version

### ISSUE THREAD

**Issue by aaime** [geoserver/geofence#28]
<a href="https://github.com/simboss"><img src="https://avatars.githubusercontent.com/u/693880?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [simboss](https://github.com/simboss)**
_Tuesday Aug 26, 2014 at 17:05 GMT_
_Originally opened as https://github.com/geosolutions-it/geofence/issues/107_

---

**Comment by etj** [comment]
Original issue is missing. Closing.
