### ISSUE TITLE
Create documentation on advanced rules management via GUI

### ISSUE THREAD

**Issue by aaime** [geoserver/geofence#33]
<a href="https://github.com/simboss"><img src="https://avatars.githubusercontent.com/u/693880?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [simboss](https://github.com/simboss)**
_Thursday Sep 04, 2014 at 08:57 GMT_
_Originally opened as https://github.com/geosolutions-it/geofence/issues/112_

---

**Comment by etj** [comment]
GWT client removed in jdk11 upgrade.
