### ISSUE TITLE
Latest Stable WAR file

### ISSUE THREAD

**Issue by cesarhein** [geoserver/geofence#52]
It's possible to put a link to the latest stable war file (v2.2.0 I think)?
I need it because is politic of my organization to deploy projects only with stable WAR files.
Thank!

**Comment by etj** [comment]
Ok, going to create a new jenkins job for deploying stable releases.

I confirm that the latest stable release is 
   https://github.com/geoserver/geofence/tree/v2.2.0

**Comment by cesarhein** [comment]
Thank you very much Emanuele!

**Comment by etj** [comment]
Jenkins job created:
   http://ares.boundlessgeo.com/jenkins/view/geofence/job/geofence%20release/

war file v2.2.0 deployed at
    http://ares.boundlessgeo.com/geofence/2.2.x/geofence-release-v2.2.0-war.zip

README updated to point to the 2.2.0 release.
    https://github.com/geoserver/geofence#release

**Comment by smeijer** [comment]
@etj, the link your providing doesn't seem to work (anymore).

Can we assume that `http://ares.boundlessgeo.com/geofence/2.2.x/geofence-2.2.x-latest-war.zip` is just as stable?

**Comment by etj** [comment]
It was removed by the script that cleans up older build by date.
I updated such script in order to only delete the nightly builds, and re-run the build job for the deploy of the release version.
