### ISSUE TITLE
Geofence with postgresql.Driver

### ISSUE THREAD

**Issue by cvpsmith** [geoserver/geofence#61]
I've tried setting up Geofence to use the PostgreSQL JDBC driver, but now it won't start properly (page times out) and I get a bunch of "gfschema" errors is the tomcat log file such as this:

15:56:26,272 ERROR SchemaUpdate:212 - Unsuccessful: create table gfschema.gf_gfuser (id int8 not null, dateCreation timestamp, emailAddress varchar(255), enabled bool not null, extId varchar(255) unique, fullName varchar(255), name varchar(255) not null unique, password varchar(255), primary key (id))
15:56:26,273 ERROR SchemaUpdate:213 - ERROR: schema "gfschema" does not exist

I edited geofence-datasource-ovr.properties with the following:

geofenceVendorAdapter.databasePlatform=org.hibernatespatial.postgis.PostgisDialect
geofenceDataSource.driverClassName=org.postgresql.Driver
geofenceDataSource.url=jdbc:postgresql://localhost:8190/geofence
geofenceDataSource.username=geofence
geofenceDataSource.password=passw0rd
geofenceEntityManagerFactory.jpaPropertyMap[hibernate.default_schema]=gfschema

I have postgresql running on port 8190 and the geofence user and databse exist.  I'm not sure what I'm doing wrong here, and I haven't found anything obvious in the documentation.  I did move the "hibernate-spatial-postgis-1.1.1.jar" to the WEB-INF/lib directory, and checked to see if I had everything else in place.  Anyone with more experience with Tomcat have any ideas on where I can start to track this down?  TIA...

**Comment by etj** [comment]
Your log reports:
```
ERROR: schema "gfschema" does not exist
```

The sample property configuration at
    https://github.com/geoserver/geofence/wiki/GeoFence-configuration#database-configuration-1
does contain the line
```
geofenceEntityManagerFactory.jpaPropertyMap[hibernate.default_schema]=gfschema
```
also stating that:

>   the schema is the DB schema where the GeoFence tables will be located; the configured user
>   should have insert/select/update grants on it; if hibernate is also requested to create the schema, 
>   some higher privileges are needed

You should create such schema in your DB, or simply set the schema to ``public``.
