### ISSUE TITLE
Geofence 3.0 on GeoServer 2.8.1  :   new rule in Geofence not active in GeoServer

### ISSUE THREAD

**Issue by GreenUtil** [geoserver/geofence#63]
Hi,

I am using the Geofence Rest API to insert a new rule.
GeoServer doesn't pick up this new rule instantly.
Only after editing the rule in the Geofence webapplication the rule will be active in GeoServer....

Is there a way of giving GeoServer a kick to reload rules from Geofence ?

I wonder if the integrated Geofence version in GeoServer 2.9 is a solution for this behaviour ?
Where can I get GeoServer 2.9 with the integrated Geofence ?

Greetings,

Barent Brouwers

The Netherlands

**Comment by etj** [comment]
Hi GreenUtil,
GeoServer uses a rule cache to avoid making too many requests, plese read this section:
    https://github.com/geoserver/geofence/wiki/Geoserver-Probe-Explained#cache-1
This is probably the section you need for forcing the new rules using the REST API:
https://github.com/geoserver/geofence/wiki/Geoserver-Probe-Explained#interacting-with-the-probe-cache-via-rest

*Please use the [geoserver mailing list](http://geoserver.org/comm/) for this kind of question.*

   Cheers,
   Emanuele
