### ISSUE TITLE
Geofence 3.0 + PostgreSQL DB, with Geoserver 2.8.1 

### ISSUE THREAD

**Issue by virjay** [geoserver/geofence#71]
Hi,
The following error shows up if a PostgreSQL DB info is added to the geofence-datasource-ovr.properties

org.springframework.remoting.RemoteAccessException: Could not access HTTP invoker remote service at [http://localhost:8081/geofence/remoting/RuleReader]; nested exception is java.io.IOException: Did not receive successful HTTP response: status code = 404, status message = [Not Found]

The 'Test Connection' link in Geoserver under the Geofence tab shows the above error and The Geofence login page is blank.

TIA
VR

**Comment by etj** [comment]
Please check the geofence log file. Probably GeoFence could not connect to the  DB, so the webapp could not be started: this explains why youdon't get anything both on your browser and through the geoserver remote call. In the log you may find more details about the connection error. 

Please report these kind of issue in the mailing list as reported [here](https://github.com/geoserver/geofence#community).
