### ISSUE TITLE
Geofence Admin rules

### ISSUE THREAD

**Issue by MarcelGeo** [geoserver/geofence#77]
Good day,

I have question about editing Geofence admin rules with REST. Is it possible to editing geofence admin rules by REST API?

**Comment by etj** [comment]
If you are using the embedded version, you can use this interface:
-    http://docs.geoserver.org/2.9.0/user/community/geofence-server/rest.html

If you are using the standalone version, you can use this one:
 -   https://github.com/geoserver/geofence/wiki/GeoFence-REST-API
 
For this kind of questions, please do not open issues, but use the GeoServer user mailing list instead:
     http://geoserver.org/comm/
