### ISSUE TITLE
Configure admin rule through rest api

### ISSUE THREAD

**Issue by ceibl58** [geoserver/geofence#79]
I use an geoserver instance with embedded geofence. I need to allow a user to administrate only his workspace. On the "geofence admin rule" page this is easily possible. But I do not know how to configure such a rule through a rest-api call. 
I read the suggested document from https://www.mail-archive.com/geoserver-users%40lists.sourceforge.net/msg25465.html but could not figure out. Setting "admin":true for the GSUser did not have the same result.

**Comment by etj** [comment]
The REST API is implemented indipendently in the standalone and in the embedded versions.

In the standalone version, the REST API for the admin rules are handled by this class:
https://github.com/geoserver/geofence/blob/master/src/services/modules/rest/impl/src/main/java/org/geoserver/geofence/services/rest/impl/RESTAdminRuleServiceImpl.java

In the embedded version the REST API is implemented by this class:
https://github.com/geoserver/geoserver/blob/master/src/community/geofence-server/src/main/java/org/geoserver/geofence/server/rest/AdminRulesRestController.java
