### ISSUE TITLE
Why multiple LIMIT rules areas geometries are intersected instead of unied ?

### ISSUE THREAD

**Issue by nmco** [geoserver/geofence#80]
When multiple LIMITS rules with an area are applied all the geometries are intersected in a single geometry: https://github.com/geoserver/geofence/blob/master/src/services/core/services-impl/src/main/java/org/geoserver/geofence/services/RuleReaderServiceImpl.java#L393

This means that if I define three LIMIT rules:

![capture d ecran de 2016-08-18 00-08-46](https://cloud.githubusercontent.com/assets/1590542/17756476/fc106ece-64d7-11e6-991b-4e8aeca46b4f.png)

with the following three areas (black dashed polygons):

![admin](https://cloud.githubusercontent.com/assets/1590542/17756521/4fa62e02-64d8-11e6-9d14-424d47390d73.png)

and **if at least two rules are applied I will always get an empty image** since he geometries of the areas do not intersect.

My expectation would be to get something like this (**I obtained the following image by joining the areas geometries instead of intersecting them**):

![filter](https://cloud.githubusercontent.com/assets/1590542/17756637/0c5a4cb8-64d9-11e6-9194-23df665795be.png)

During my tests I change the code to perform an union:

```
g = g.union(area);
```

instead of an intersection and all the tests passed.

**Comment by etj** [comment]
Security rules are usually processed in the more restrictive way, so if different limiting rules have different accessibile areas, the resulting area is the one permitted by all the rules, so we need the intersection operation on the areas.

Also note that if a user belongs to more than one group, the permissions are merged inclusively, so if the groups allow the access to different areas, they will be UNIONed; in the same way, if the attribute list is limited in one or both groups, the returned accessibile attributes will be the union of the allowed ones, with the most permissive access type (RW/RO).

**Comment by nmco** [comment]
Yeah it makes sense thanks for the feedback Emanuele :)
