### ISSUE TITLE
Pagination icons are missing

### ISSUE THREAD

**Issue by Gnafu** [geoserver/geofence#91]
Tabs with multiple pages don't have navigation icons, except when on first and last page.

![2017-04-18_1707](https://cloud.githubusercontent.com/assets/3932165/25137972/8a58e9fe-2459-11e7-97bb-8430b87cf490.png)

![2017-04-18_1708](https://cloud.githubusercontent.com/assets/3932165/25137995/9d54acdc-2459-11e7-9873-bf96fc269442.png)

![2017-04-18_1708_001](https://cloud.githubusercontent.com/assets/3932165/25138012/ab119fec-2459-11e7-8180-f55a31ec1a42.png)

**Comment by etj** [comment]
GWT client removed in jdk11 upgrade.
