### ISSUE TITLE
Issue with transactions on H2

### ISSUE THREAD

**Issue by capooti** [geoserver/geofence#98]
Using GeoFence with H2 I have noticed that when using a large number of transactions in a small time, some transactions get lost. If I split the large number of transactions in a larger time than they are all executed successfully.
I am wondering if it is an H2 limit (in which case I can move to PostgreSQL) or a bug of GeoFence.

**Comment by etj** [comment]
It's hard to investigate without any test case or a way to replicate the issue.
Do you have any evidence of errors or stacktrace?

**Comment by etj** [comment]
GeoFence uses hibernate on top of JDBC drivers. There are no timing or other limintation in GeoFence, so it's quite plausible that the problem il related ot H2. Pls prefer using postgres for production use.
